[package]
name = "rust_morse"
version = "0.1.0"
authors = ["scott-olson <scotteolson3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
beep = "0.2.1"
dimensioned = "0.6.0"
